#!/bin/bash

echo MODE=$MODE
echo NUM_EPOCHS=$NUM_EPOCHS
echo BATCH_SIZE=$BATCH_SIZE
echo SAVE_PATH=$SAVE_PATH
echo TOP_DB=$TOP_DB 
echo HIDDEN_SIZE=$HIDDEN_SIZE
echo FC_HIDDEN_SIZE=$FC_HIDDEN_SIZE
echo MODEL_TYPE=$MODEL_TYPE
echo WINDOW_SIZE=$WINDOW_SIZE